/**
 * Composable for managing Component Natures
 * Uses singleton pattern - state is shared across all component instances
 *
 * This composable is generated by composableFactory from entityRegistry configuration.
 * All CRUD operations, search functionality, and computed properties are dynamically created.
 */

import { createEntityComposable } from '@/composables/composableFactory';
import { entities } from '@/composables/entityRegistry';

/**
 * Component Natures composable
 * Generated from factory with configuration for:
 * - State: componentNatures, isLoading, error, isInitialized
 * - Methods: fetchComponentNatures, initialize, searchComponentNatures,
 *           getComponentNatureById, createComponentNature, updateComponentNature, deleteComponentNature
 * - Computed: totalComponentNatures, activeComponentNatures
 */
export const useComponentNatures = createEntityComposable(entities.componentNatures);
