/**
 * Composable for managing Component Statuses
 * Uses singleton pattern - state is shared across all component instances
 *
 * This composable is generated by composableFactory from entityRegistry configuration.
 * All CRUD operations, search functionality, and computed properties are dynamically created.
 */

import { createEntityComposable } from '@/composables/composableFactory';
import { entities } from '@/composables/entityRegistry';

/**
 * Component Statuses composable
 * Generated from factory with configuration for:
 * - State: componentStatuses, isLoading, error, isInitialized
 * - Methods: fetchComponentStatuses, initialize, searchComponentStatuses,
 *           getComponentStatusById, createComponentStatus, updateComponentStatus, deleteComponentStatus
 * - Computed: totalComponentStatuses, activeComponentStatuses,
 *            availableStatuses, operationalStatuses, physicallyPresentStatuses, inventoryStatuses,
 *            installableStatuses, attentionRequiredStatuses, transitionStatuses
 */
export const useComponentStatuses = createEntityComposable(entities.componentStatuses);
