/**
 * Composable for managing Component Models
 * Uses singleton pattern - state is shared across all component instances
 *
 * This composable is generated by composableFactory from entityRegistry configuration.
 * All CRUD operations, search functionality, and computed properties are dynamically created.
 */

import { createEntityComposable } from '@/composables/composableFactory';
import { entities } from '@/composables/entityRegistry';

/**
 * Component Models composable
 * Generated from factory with configuration for:
 * - State: componentModels, isLoading, error, isInitialized
 * - Methods: fetchComponentModels, initialize, searchComponentModels,
 *           getComponentModelById, createComponentModel, updateComponentModel, deleteComponentModel
 * - Computed: totalComponentModels, activeComponentModels,
 *            discontinuedModels, endOfLifeModels, verifiedModels
 */
export const useComponentModels = createEntityComposable(entities.componentModels);
