/**
 * Composable for managing Component Types
 * Uses singleton pattern - state is shared across all component instances
 *
 * This composable is generated by composableFactory from entityRegistry configuration.
 * All CRUD operations, search functionality, and computed properties are dynamically created.
 */

import { createEntityComposable } from '@/composables/composableFactory';
import { entities } from '@/composables/entityRegistry';

/**
 * Component Types composable
 * Generated from factory with configuration for:
 * - State: componentTypes, isLoading, error, isInitialized
 * - Methods: fetchComponentTypes, initialize, searchComponentTypes,
 *           getComponentTypeById, createComponentType, updateComponentType, deleteComponentType
 * - Computed: totalComponentTypes, activeComponentTypes,
 *            systemTypes, userTypes, housingTypes, connectivityTypes, supportTypes, moduleTypes, networkingTypes
 */
export const useComponentTypes = createEntityComposable(entities.componentTypes);
