/**
 * Composable for managing Component Categories
 * Uses singleton pattern - state is shared across all component instances
 *
 * This composable is generated by composableFactory from entityRegistry configuration.
 * All CRUD operations, search functionality, and computed properties are dynamically created.
 */

import { createEntityComposable } from '@/composables/composableFactory';
import { entities } from '@/composables/entityRegistry';

/**
 * Component Categories composable
 * Generated from factory with configuration for:
 * - State: componentCategories, isLoading, error, isInitialized
 * - Methods: fetchComponentCategories, initialize, searchComponentCategories,
 *           getComponentCategoryById, createComponentCategory, updateComponentCategory, deleteComponentCategory
 * - Computed: totalComponentCategories, activeComponentCategories,
 *            systemCategories, userCategories, infrastructureCategories
 */
export const useComponentCategories = createEntityComposable(entities.componentCategories);
