/**
 * Composable for managing Installation Statuses
 * Uses singleton pattern - state is shared across all component instances
 *
 * This composable is generated by composableFactory from entityRegistry configuration.
 * All CRUD operations, search functionality, and computed properties are dynamically created.
 */

import { createEntityComposable } from '@/composables/composableFactory';
import { entities } from '@/composables/entityRegistry';

/**
 * Installation Statuses composable
 * Generated from factory with configuration for:
 * - State: installationStatuses, isLoading, error, isInitialized
 * - Methods: fetchInstallationStatuses, initialize, searchInstallationStatuses,
 *           getInstallationStatusById, createInstallationStatus, updateInstallationStatus, deleteInstallationStatus
 * - Computed: totalInstallationStatuses, activeStatuses,
 *            physicallyPresentStatuses, operationalStatuses, attentionRequiredStatuses, finalStatuses,
 *            errorStatuses, autoTransitionStatuses, progressStatuses, successStatuses, warningStatuses, terminalStatuses
 */
export const useInstallationStatuses = createEntityComposable(entities.installationStatuses);
