/**
 * Composable for managing Installable Types
 * Uses singleton pattern - state is shared across all component instances
 *
 * This composable is generated by composableFactory from entityRegistry configuration.
 * All CRUD operations, search functionality, and computed properties are dynamically created.
 */

import { createEntityComposable } from '@/composables/composableFactory';
import { entities } from '@/composables/entityRegistry';

/**
 * Installable Types composable
 * Generated from factory with configuration for:
 * - State: installableTypes, isLoading, error, isInitialized
 * - Methods: fetchInstallableTypes, initialize, searchInstallableTypes,
 *           getInstallableTypeById, createInstallableType, updateInstallableType, deleteInstallableType
 * - Computed: totalInstallableTypes, activeTypes,
 *            deviceTypes, connectivityTypes, housingTypes, powerTypes, rackMountable, hotSwappableTypes,
 *            powerManagedTypes, environmentalControlTypes, highPriorityTypes, lowPriorityTypes, specialHandlingTypes
 */
export const useInstallableTypes = createEntityComposable(entities.installableTypes);
