/**
 * Composable for managing Location Types
 * Uses singleton pattern - state is shared across all component instances
 *
 * This composable is generated by composableFactory from entityRegistry configuration.
 * All CRUD operations, search functionality, and computed properties are dynamically created.
 */

import { createEntityComposable } from '@/composables/composableFactory';
import { entities } from '@/composables/entityRegistry';

/**
 * Location Types composable
 * Generated from factory with configuration for:
 * - State: locationTypes, isLoading, error, isInitialized
 * - Methods: fetchLocationTypes, initialize, searchLocationTypes,
 *           getLocationTypeById, createLocationType, updateLocationType, deleteLocationType
 * - Computed: totalLocationTypes, activeLocationTypes,
 *            topLevelTypes, middleLevelTypes, bottomLevelTypes, physicalTypes, virtualTypes,
 *            buildingLikeTypes, roomLikeTypes, rackLikeTypes, datacenterLikeTypes, secureTypes
 */
export const useLocationTypes = createEntityComposable(entities.locationTypes);
