/**
 * Detail View Configuration for Network Switch
 */

export default {
  tableKey: 'networkSwitches',
  composable: 'useNetworkSwitches',

  sections: {
    basicInfo: {
      fields: [
        { key: 'name', label: 'Name', fallback: '-' },
        { key: 'description', label: 'Description', fallback: 'No description' },
        { key: 'manufacturer', label: 'Manufacturer', fallback: 'N/A' },
        { key: 'model', label: 'Model', fallback: 'N/A' },
        { key: 'serialNumber', label: 'Serial Number', fallback: 'N/A' },
        { key: 'partNumber', label: 'Part Number', fallback: 'N/A' },
        { key: 'ipAddress', label: 'IP Address', fallback: 'N/A' },
        { key: 'hostname', label: 'Hostname', fallback: 'N/A' },
        { key: 'managementIp', label: 'Management IP', fallback: 'N/A' },
        { key: 'subnetMask', label: 'Subnet Mask', fallback: 'N/A' },
        { key: 'defaultGateway', label: 'Default Gateway', fallback: 'N/A' },
        { key: 'managementVlan', label: 'Management VLAN', fallback: '-' },
        { key: 'componentTypeDisplayName', label: 'Switch Type', fallback: '-' },
        { key: 'componentTypeCode', label: 'Type Code', fallback: '-' },
        { key: 'componentStatusDisplayName', label: 'Status', fallback: '-' },
        { key: 'componentStatusCode', label: 'Status Code', fallback: '-' },
        { key: 'componentNatureCode', label: 'Nature Code', fallback: '-' },
        { key: 'operational', label: 'Operational', type: 'boolean' },
        { key: 'installed', label: 'Installed', type: 'boolean' },
        { key: 'managed', label: 'Managed', type: 'boolean' },
        { key: 'reachable', label: 'Reachable', type: 'boolean' },
        { key: 'monitoringStatus', label: 'Monitoring Status', fallback: '-' },
        { key: 'networkConfiguration', label: 'Network Configuration', fallback: '-' },
        { key: 'portCount', label: 'Port Count', fallback: '-' },
        { key: 'firmwareVersion', label: 'Firmware Version', fallback: 'N/A' },
        { key: 'softwareVersion', label: 'Software Version', fallback: 'N/A' },
        { key: 'bootLoaderVersion', label: 'Boot Loader Version', fallback: 'N/A' },
        { key: 'monitored', label: 'Monitored', type: 'boolean' },
        { key: 'monitoringIntervalSeconds', label: 'Monitoring Interval (s)', fallback: '-' },
        { key: 'lastPingTime', label: 'Last Ping Time', format: 'date', fallback: '-' },
        { key: 'lastPingSuccess', label: 'Last Ping Success', type: 'boolean' },
        { key: 'uptimeSeconds', label: 'Uptime (s)', fallback: '-' },
        { key: 'consolePortType', label: 'Console Port Type', fallback: 'N/A' },
        { key: 'hasRedundantPower', label: 'Redundant Power', type: 'boolean' },
        { key: 'operatingTemperatureMin', label: 'Operating Temp Min (°C)', fallback: '-' },
        { key: 'operatingTemperatureMax', label: 'Operating Temp Max (°C)', fallback: '-' },
        { key: 'cpuUtilizationPercent', label: 'CPU Utilization (%)', fallback: '-' },
        { key: 'memoryUtilizationPercent', label: 'Memory Utilization (%)', fallback: '-' },
        { key: 'temperatureCelsius', label: 'Temperature (°C)', fallback: '-' },
        { key: 'switchModelName', label: 'Switch Model', fallback: '-' },
        { key: 'maxPorts', label: 'Max Ports', fallback: '-' },
        { key: 'supportsPoe', label: 'Supports PoE', type: 'boolean' },
        { key: 'poeBudgetWatts', label: 'PoE Budget (W)', fallback: '-' },
        { key: 'poeCapability', label: 'PoE Capability', type: 'boolean' },
        { key: 'availablePoeBudget', label: 'Available PoE Budget (W)', fallback: '-' },
        { key: 'supportsStacking', label: 'Supports Stacking', type: 'boolean' },
        { key: 'stackable', label: 'Stackable', type: 'boolean' },
        { key: 'inStack', label: 'In Stack', type: 'boolean' },
        { key: 'stackMaster', label: 'Stack Master', type: 'boolean' },
        { key: 'stackId', label: 'Stack ID', fallback: '-' },
        { key: 'stackPriority', label: 'Stack Priority', fallback: '-' },
        { key: 'maxStackMembers', label: 'Max Stack Members', fallback: '-' },
        { key: 'switchingCapacityGbps', label: 'Switching Capacity (Gbps)', fallback: '-' },
        { key: 'forwardingRateMpps', label: 'Forwarding Rate (Mpps)', fallback: '-' },
        { key: 'macAddressTableSize', label: 'MAC Table Size', fallback: '-' },
        { key: 'vlanSupport', label: 'VLAN Support', type: 'boolean' },
        { key: 'maxVlans', label: 'Max VLANs', fallback: '-' },
        { key: 'spanningTreeSupport', label: 'Spanning Tree Support', type: 'boolean' },
        { key: 'qosSupport', label: 'QoS Support', type: 'boolean' },
        { key: 'portMirroring', label: 'Port Mirroring', type: 'boolean' },
        { key: 'linkAggregation', label: 'Link Aggregation', type: 'boolean' },
        { key: 'nativeVlan', label: 'Native VLAN', fallback: '-' },
        { key: 'voiceVlan', label: 'Voice VLAN', fallback: '-' },
        { key: 'packetBufferSizeMb', label: 'Packet Buffer (MB)', fallback: '-' },
        { key: 'componentPath', label: 'Component Path', fallback: '-' },
        { key: 'locationAddress', label: 'Location Address', fallback: '-' },
        { key: 'installationId', label: 'Installation ID', fallback: '-' },
        { key: 'parentComponentName', label: 'Parent Component', fallback: '-' },
        { key: 'parentComponentId', label: 'Parent Component ID', fallback: '-' },
        { key: 'lastMaintenanceDate', label: 'Last Maintenance', format: 'date', fallback: '-' },
        { key: 'nextMaintenanceDate', label: 'Next Maintenance', format: 'date', fallback: '-' }
      ]
    }
  }
};
