/**
 * Detail View Configuration for Port
 */

export default {
  tableKey: 'ports',
  composable: 'usePorts',

  sections: {
    basicInfo: {
      fields: [
        { key: 'name', label: 'Name', fallback: '-' },
        { key: 'description', label: 'Description', fallback: 'No description' },
        { key: 'deviceName', label: 'Device', fallback: '-' },
        { key: 'deviceId', label: 'Device ID', fallback: '-' },
        { key: 'connectorName', label: 'Connector', fallback: '-' },
        { key: 'connectorId', label: 'Connector ID', fallback: '-' },
        { key: 'portNumber', label: 'Port Number', fallback: '-' },
        { key: 'portLabel', label: 'Port Label', fallback: '-' },
        { key: 'status', label: 'Status', fallback: '-' },
        { key: 'adminStatus', label: 'Admin Status', fallback: '-' },
        { key: 'operationalStatus', label: 'Operational Status', fallback: '-' },
        { key: 'speedMbps', label: 'Speed (Mbps)', fallback: '-' },
        { key: 'maxSpeedMbps', label: 'Max Speed (Mbps)', fallback: '-' },
        { key: 'speedGbps', label: 'Speed (Gbps)', fallback: '-' },
        { key: 'maxSpeedGbps', label: 'Max Speed (Gbps)', fallback: '-' },
        { key: 'duplexMode', label: 'Duplex Mode', fallback: '-' },
        { key: 'autoNegotiation', label: 'Auto Negotiation', type: 'boolean' },
        { key: 'connectorType', label: 'Connector Type', fallback: '-' },
        { key: 'mediumType', label: 'Medium Type', fallback: '-' },
        { key: 'accessVlan', label: 'Access VLAN', fallback: '-' },
        { key: 'nativeVlan', label: 'Native VLAN', fallback: '-' },
        { key: 'portMode', label: 'Port Mode', fallback: '-' },
        { key: 'poeEnabled', label: 'PoE Enabled', type: 'boolean' },
        { key: 'poeClass', label: 'PoE Class', fallback: '-' },
        { key: 'poePowerWatts', label: 'PoE Power (W)', fallback: '-' },
        { key: 'poeMaxPowerWatts', label: 'PoE Max Power (W)', fallback: '-' },
        { key: 'bytesIn', label: 'Bytes In', fallback: '-' },
        { key: 'bytesOut', label: 'Bytes Out', fallback: '-' },
        { key: 'packetsIn', label: 'Packets In', fallback: '-' },
        { key: 'packetsOut', label: 'Packets Out', fallback: '-' },
        { key: 'errorsIn', label: 'Errors In', fallback: '-' },
        { key: 'errorsOut', label: 'Errors Out', fallback: '-' },
        { key: 'discardsIn', label: 'Discards In', fallback: '-' },
        { key: 'discardsOut', label: 'Discards Out', fallback: '-' },
        { key: 'lastChange', label: 'Last Change', format: 'date', fallback: '-' },
        { key: 'lastActivity', label: 'Last Activity', format: 'date', fallback: '-' },
        { key: 'statsLastReset', label: 'Stats Last Reset', format: 'date', fallback: '-' },
        { key: 'configurationNotes', label: 'Configuration Notes', fallback: '-' },
        { key: 'monitoringEnabled', label: 'Monitoring Enabled', type: 'boolean' },
        { key: 'portType', label: 'Port Type', fallback: '-' },
        { key: 'up', label: 'Up', type: 'boolean' },
        { key: 'down', label: 'Down', type: 'boolean' },
        { key: 'adminEnabled', label: 'Admin Enabled', type: 'boolean' },
        { key: 'available', label: 'Available', type: 'boolean' },
        { key: 'connected', label: 'Connected', type: 'boolean' },
        { key: 'poeCapable', label: 'PoE Capable', type: 'boolean' },
        { key: 'poePowered', label: 'PoE Powered', type: 'boolean' },
        { key: 'trunkPort', label: 'Trunk Port', type: 'boolean' },
        { key: 'accessPort', label: 'Access Port', type: 'boolean' },
        { key: 'utilizationPercent', label: 'Utilization (%)', fallback: '-' },
        { key: 'totalPackets', label: 'Total Packets', fallback: '-' },
        { key: 'totalBytes', label: 'Total Bytes', fallback: '-' },
        { key: 'totalErrors', label: 'Total Errors', fallback: '-' },
        { key: 'errorRate', label: 'Error Rate', fallback: '-' },
        { key: 'ethernetStandard', label: 'Ethernet Standard', fallback: '-' },
        { key: 'mdiMdixMode', label: 'MDI/MDIX Mode', fallback: '-' },
        { key: 'cableLengthMeters', label: 'Cable Length (m)', fallback: '-' },
        { key: 'linkPartnerInfo', label: 'Link Partner Info', fallback: '-' },
        { key: 'gigabitCapable', label: 'Gigabit Capable', type: 'boolean' },
        { key: 'tenGigabitCapable', label: '10G Capable', type: 'boolean' },
        { key: 'ethernetClass', label: 'Ethernet Class', fallback: '-' },
        { key: 'fiberType', label: 'Fiber Type', fallback: '-' },
        { key: 'wavelengthNm', label: 'Wavelength (nm)', fallback: '-' },
        { key: 'fiberStandard', label: 'Fiber Standard', fallback: '-' },
        { key: 'transmissionDistanceKm', label: 'Transmission Distance (km)', fallback: '-' },
        { key: 'txPowerDbm', label: 'TX Power (dBm)', fallback: '-' },
        { key: 'rxPowerDbm', label: 'RX Power (dBm)', fallback: '-' },
        { key: 'opticalLossDb', label: 'Optical Loss (dB)', fallback: '-' },
        { key: 'singleMode', label: 'Single Mode', type: 'boolean' },
        { key: 'multiMode', label: 'Multi Mode', type: 'boolean' },
        { key: 'hasOpticalSignal', label: 'Optical Signal', type: 'boolean' },
        { key: 'opticalLinkHealthy', label: 'Optical Link Healthy', type: 'boolean' },
        { key: 'opticalLinkQuality', label: 'Optical Link Quality', fallback: '-' }
      ]
    }
  }
};
